using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AddressableAssets;

/// <summary>
/// Monobehaviour placed on objects generated by ObjectPools; OnDestroy removes this instance of the object from its ObjectPool
/// </summary>
public class ObjectPoolObject : MonoBehaviour
{
    public AssetReference assetReference;
    public event Action<AssetReference, ObjectPoolObject> Destroyed;
    public event Action<AssetReference, ObjectPoolObject> Disabled;

    public void OnDestroy()
    {
        Destroyed?.Invoke(assetReference, this);
    }

    //Add the disabled object back into the pool
    public void OnDisable()
    {
        Disabled?.Invoke(assetReference, this);
    }
}
